# Generated by Django 3.2.3 on 2021-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_default.jpg', upload_to='product_images/'),
        ),
    ]
